# ========== 业务配置 ==========
# 在 Nacos 控制台创建:
#   Namespace: shiyue
#   Group:     DEFAULT_GROUP
#   Data ID:   chenxu-demo.yaml
# =================================

spring:
  kafka:
    bootstrap-servers: 192.168.249.129:9092
    consumer:
      group-id: cx-hash-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        acks: all
        retries: 10
        max.in.flight.requests.per.connection: 5
        batch.size: 16384
        linger.ms: 5
        request.timeout.ms: 30000
        metadata.max.age.ms: 300000
  data:
    redis:
      port: 6379
      password: snCJadmin-1
      host: 192.168.249.129
      database: 0
      timeout: 5000
  datasource:
    url: jdbc:mysql://192.168.249.129:3306/austin?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: snCJadmin-1
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.redis.load

kafka:
  topic: HASH_PAR_CX
  partitions: 3
