# ============================================
# Secret — 密码/密钥等敏感信息
# ⚠️ 生产环境应用 SealedSecret 或 ExternalSecrets 替代
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: chenxu
type: Opaque
stringData:
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD: "snCJadmin-1"
  REDIS_PASSWORD: "snCJadmin-1"
  JWT_SECRET: "chenxu-demo-jwt-secret-key-2026-shiyue"
